### ISSUE TITLE
detailed instructions how to use homebrew

### ISSUE THREAD

**Issue by rubo77** [Moonbase59/loudgain#30]
I installed homebrew on my linux Ubuntu 20.04 with the install script on brew.sh, then I tried to follow the README, but failed:

     brew update 
     brew: Befehl nicht gefunden.
I had to add an alias for the `brew` command:

    alias brew=/home/linuxbrew/.linuxbrew/bin/brew

Then the command in the Readme failed:

    brew uninstall --ignore-dependencies libtag
> Error: No installed keg or cask with the name "libtag"

but the install worked fine:

```
brew install --HEAD libtag
...
brew install Moonbase59/tap/loudgain
...
```

until:
```
==> Downloading from https://codeload.github.com/Moonbase59/loudgain/tar.gz/v0.6.8
curl: (22) The requested URL returned error: 500 Internal Server Error        
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries 
Warning: left.
curl: (22) The requested URL returned error: 500 Internal Server Error        
Warning: Transient problem: HTTP error Will retry in 2 seconds. 2 retries 
Warning: left.
curl: (22) The requested URL returned error: 500 Internal Server Error        
Warning: Transient problem: HTTP error Will retry in 4 seconds. 1 retries 
Warning: left.
curl: (22) The requested URL returned error: 500 Internal Server Error        

Error: Failed to download resource "loudgain"
Download failed: https://github.com/Moonbase59/loudgain/archive/v0.6.8.tar.gz
```

**Comment by rubo77** [comment]
And it is not clear when do you need the "Dependencies"?

I tried this:

```
sudo apt install libavcodec libavformat libavutil libswresample libebur128  libtag
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libavcodec
E: Unable to locate package libavformat
E: Unable to locate package libavutil
E: Unable to locate package libswresample
E: Unable to locate package libebur128
E: Unable to locate package libtag

**Comment by rubo77** [comment]
The 

> Download failed: https://github.com/Moonbase59/loudgain/archive/v0.6.8.tar.gz
This seems fixed, it was a temporary offlinage of large parts of GitHub

**Comment by rubo77** [comment]
And how do you use it after installation?

I tried

```
$ cd /myMp3MusicFolder
$ /home/linuxbrew/.linuxbrew/bin/rgbpm .
rgbpm requires "mp3gain2" but it's not installed. Aborting.
sudo apt install mp3gain2
E: Unable to locate package mp3gain2

```

**Comment by rubo77** [comment]
I fixed that with

    cd /usr/local/bin
    sudo ln -s mp3gain mp3gain2

now `metaflac` is missing, fixed that with

    apt install flac

**Comment by Moonbase59** [comment]
Phew, what a can of worms! I made and tested the HomeBrew variant primarily for Mac users, and never assumed anyone would use brew on a Linux system. It’s quite easy to compile, or one could use the provided binary and simply put it in the user’s `~/bin` or another place where the system can find it.

Sorry to say, but I currently don’t have the time to investigate brew on Linux.
