### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by wombalton** [Moonbase59/loudgain#36]
@Moonbase59 : Is this still active, there is no commit since a year ago! And open pull requests...
Hope this nice program is not dieing as well

**Comment by Moonbase59** [comment]
Be assured it won’t die … ;-)

But I’m currently still working on such a lot of other stuff that I just don’t have the time to work on loudgain. It does what it should, for a lot of people, even on Mac and in Windows 10’s "bash box".

But I’ll certainly still listen to ideas and bug reports, and there will come a time when I can work again on loudgain.
