### ISSUE TITLE
"Could not open SWResample: Invalid argument" for ALAC and WAV files

### ISSUE THREAD

**Issue by Moonbase59** [Moonbase59/loudgain#4]
@classicjazz reports:

```
$ loudgain -L -a -k -s e *.m4a
[✔] Scanning '08 Photograph.m4a' ...
[✘] Could not open SWResample: Invalid argument
```
on a Mac.

**Comment by Moonbase59** [comment]
I downloaded [18 MacCunn The Lay of the Last Minstrel - Part 2.M4A](http://www.hyperion-records.co.uk/audiotest/18%20MacCunn%20The%20Lay%20of%20the%20Last%20Minstrel%20-%20Part%202%20Final%20chorus%20O%20Caledonia!%20stern%20and%20wild.M4A) from the [Hyperion testfiles page](http://www.hyperion-records.co.uk/testfiles.asp) and tried … out put in next comment because I must switch machines …

**Comment by Moonbase59** [comment]
```
Matthiass-iMac:Documents matthias$ loudgain -L -a -k -s e *.M4A
[✔] Scanning '18 MacCunn The Lay of the Last Minstrel - Part 2 Final chorus O Caledonia! stern and wild.M4A' ...
 100% [========================================================================]

Track: 18 MacCunn The Lay of the Last Minstrel - Part 2 Final chorus O Caledonia! stern and wild.M4A
 Loudness:   -15.18 LUFS
 Range:       15.39 dB
 Peak:     0.971494 (-0.25 dBTP)
 Gain:        -2.82 dB

Album:
 Loudness:   -15.18 LUFS
 Range:       15.39 dB
 Peak:     0.971494 (-0.25 dBTP)
 Gain:        -2.82 dB
Matthiass-iMac:Documents matthias$ 
```

**Comment by Moonbase59** [comment]
Could you try
```
ffmpeg -i '08 Photograph.m4a'
```
to verify your file?

**Comment by Moonbase59** [comment]
Thanks for your sample. I tried it here and it works:
```
Matthiass-iMac:Downloads matthias$ loudgain -L -a -k -s e *.m4a
[✔] Scanning '08 Photograph.m4a' ...
 100% [========================================================================]

Track: 08 Photograph.m4a
 Loudness:   -10.35 LUFS
 Range:       12.19 dB
 Peak:     1.058455 (0.49 dBTP)
 Gain:        -7.65 dB

Album:
 Loudness:   -10.35 LUFS
 Range:       12.19 dB
 Peak:     1.058455 (0.49 dBTP)
 Gain:        -7.65 dB
Matthiass-iMac:Downloads matthias$ 
```
I think there must be some difference between our installations, I suspect the FFmpeg version maybe? I got version 4.1.4 when brew installing it.

**Comment by classicjazz** [comment]
Yes (per my email), I am running FFMPEG head due to MPV dependencies. I will uninstall all dependencies and verify with FFMPEG's current release.

**Comment by classicjazz** [comment]
Confirmed, loudgain works with release FFMPEG but not the latest FFMPEG (4.2).

I suspect you are already on this issue based on the new release notes:

"Had to postpone this release because FFmpeg 4.2 breaks the old API (deprecated calls no longer working). Some rework needed before release."

**Comment by Moonbase59** [comment]
Yes, exactly. We’ve been using "older" calls into the FFmpeg libraries that got deprecated in the meantime, and today FFmpeg 4.2 came out that broke the API … :-( Talking about "won’t make a problem" … hee hee. I’m currently investigating and rewriting the scanner code. The last FFmpeg version where the "old" calls worked was 4.1.4.

Working on it … :-)

**Comment by Moonbase59** [comment]
You might want to try new loudgain v0.6.0. Should work using either manual build or brew install, with FFmpeg 4.1.4 as well as 4.2. Took me a while to iron this out.

**Comment by classicjazz** [comment]
Confirmed that loudgain now works well with FFMPEG HEAD (4.2 as homebrew stable is still 4.1).

Also confirmed that rgbpm works for mass tagging. But still investigating why it says "Skipping BPM calculation ..."

**Comment by classicjazz** [comment]
rgbpm: No 'bpm-calc' found, BPM calculation will be skipped!

**Comment by Moonbase59** [comment]
Easy explantion, hee hee: I wrote that script a LONG time ago for myself and some friends, using a conglomerate of obscure vamp plugins, scripts and the `sonic-annotator` from the Queen Mary University of London. Since I’m lazy and just planned to support _one_ script, I just copied mine over ;-) … which of course doesnt’t find all that stuff. But if you have a good bpm calculator script, just name it `bpm-calc` and it can work like a "plug-in".

So it’s actually just a notice that it’ll only do the loudgaining.

Thanks for your testing!

**Comment by Teteros** [comment]
Sadly I've got the issue still with ffmpeg 4.2 (and ffmpeg 4.1.3 if I rollback) on Arch Linux
```
loudgain some.wav
[✔] Scanning 'some.wav' ...
[✔] Stream #0: PCM signed 16-bit little-endian
[✘] Could not open SWResample: Invalid argument
loudgain -version
loudgain 0.6.0 - using:
  libebur128 1.2.4
  libavformat 58.29.100
  libswresample 3.5.100
ffmpeg -version
ffmpeg version n4.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-
libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-l
ibmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libth
eora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enabl
e-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by Teteros** [comment]
Hm, actually it could be the .wav file because I've tried an mp3 (with static build to rule out my libs) and it worked:

```
./loudgain.static a.mp3
[✔] Scanning 'nq-bad_apple.mp3' ...
[✔] Stream #0: MP3 (MPEG audio layer 3)
 100% [===================================================================================================================================================================================]

Track: nq-bad_apple.mp3
 Loudness:    -9.56 LUFS
 Range:        3.35 dB
 Peak:     1.120602 (0.99 dBTP)
 Gain:        -8.44 dB
./loudgain.static some.wav
[✔] Scanning 'some.wav' ...
[✔] Stream #0: PCM signed 16-bit little-endian
[✘] Could not open SWResample: Invalid argument
```
Sorry for the noise :S

**Comment by Moonbase59** [comment]
Yep, loudgain doesn’t (yet?) work on .wav files, sorry.

**Comment by Moonbase59** [comment]
Try out v0.6.1. This version has some bugfixes regarding multi-channel files and can _read almost anything_, maybe this helps.

It can still _not_ tag WAV files, since there is no accepted standard that all players would recognise. Some ReplayGain tools add ID3v2 frames, others introduce non-standard entries in the RIFF chunks, but nothing is really compatible (except with itself).

My recommendation—if anyhow possible—would be to switch to a format like FLAC (or maybe ALAC if you’re on a Mac) which are also lossless, have smaller file sizes and can be tagged easily.

**Comment by Moonbase59** [comment]
If you intend to do some further processing, there’s always the option to use loudgain’s `-O` output for that. Here is an example that would just show columns 1 (filename) and 9 (desired ReplayGain):

```bash
$ loudgain -O -k *.wav | awk -v FS='\t' '{print $1 ";" $9}'
[✔] Scanning 'some.wav' ...
[✔] Stream #0: PCM signed 16-bit little-endian, 16 bit, 44100 Hz, 1 ch, mono
[✔] Scanning 'Spiral Skies - Awakening.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Black Hole Waltz.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Danse Macabre.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Dark Side of the Cross.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Labyrinth of the Mind.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Left Is Right and Right Is Left Behind.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - Shattered Hopes.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - The Prisoner.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
[✔] Scanning 'Spiral Skies - The Wizard's Ball.wav' ...
[✔] Stream #0: PCM signed 24-bit little-endian, 24 bit, 44100 Hz, 2 ch, stereo
File;Gain
some.wav;10.51 dB
Spiral Skies - Awakening.wav;-8.25 dB
Spiral Skies - Black Hole Waltz.wav;-5.15 dB
Spiral Skies - Danse Macabre.wav;-7.19 dB
Spiral Skies - Dark Side of the Cross.wav;-8.36 dB
Spiral Skies - Labyrinth of the Mind.wav;-7.79 dB
Spiral Skies - Left Is Right and Right Is Left Behind.wav;-8.15 dB
Spiral Skies - Shattered Hopes.wav;-8.51 dB
Spiral Skies - The Prisoner.wav;-8.21 dB
Spiral Skies - The Wizard's Ball.wav;-8.12 dB
```

**Comment by Teteros** [comment]
> Loudgain can still not tag WAV files, since there is no accepted standard that all players would recognise. Some ReplayGain tools add ID3v2 frames, others introduce non-standard entries in the RIFF chunks, but nothing is really compatible (except with itself).

@Moonbase59 BWF (Broadcast Wave Format) extension to WAV version 2 supports loudness tags (`LoudnessValue` `LoudnessRange` `MaxTruePeakLevel` `MaxMomentaryLoudness` `MaxShortTermLoudness`) and it's read/output by DAWs so it might be worth looking into
https://tech.ebu.ch/docs/tech/tech3285.pdf

[r128gain](http://r128gain.sourceforge.net/) which is another ffmpeg based normalizer supports it

**Comment by classicjazz** [comment]
As Matthias suggests, converting your WAV files to FLAC or ALAC is win-win. You save disk space.  There is little computational overhead. You don't lose quality because both are lossless compression methods. And you also gain standardized tag support.

**Comment by Moonbase59** [comment]
You’re both right, @Teteros and @classicjazz: For the "normal" user, FLAC/ALAC would be the way to go, but in real production and broadcasting WAV ist still very much (if not mostly) used. I wasn’t aware of _Tech 3285_ which would actually be nice to implement, I agree. Even more interesting since we have all the values (M,S,I) internally.

Unfortunately, the [TagLib](https://taglib.org/) library I use only supports ID3 (no, no!) and at max. the RIFF 'LIST' 'INFO' chunk (and not the _'bext'_ chunk which we need). It won’t be possible for me in the near future to write and debug a lot of TagLib subclasses to handle all that, but you might want to [file an issue](https://github.com/taglib/taglib/issues) at upstream TagLib to make it known this feature is _needed_ in the professional area. (I found out that even Tascams use the BWF data!)

**Comment by Moonbase59** [comment]
Please also support [issue #479 in libsndfile](https://github.com/erikd/libsndfile/issues/479) — thanks!
I might end up using `libsndfile` for WAV (BWF) tagging.

**Comment by Moonbase59** [comment]
@Teteros: You might want to experiment with **v0.6.5** of loudgain, which **adds rudimentary WAV support** (by writing ID3v2 data into the "ID3 " chunk, for now ignoring the "bext" chunk). I don’t much like this kind of tagging, but it is compatible with _foobar2000_, _VLC_, _Mp3tag_ and some others.

Please have a backup before testing, and read [How I handle WAV (.wav) audio files](https://github.com/Moonbase59/loudgain#how-i-handle-wav-wav-audio-files).
