### ISSUE TITLE
Docker Image of Loudgain

### ISSUE THREAD

**Issue by rosscullen** [Moonbase59/loudgain#41]
Great project @Moonbase59 ... would you consider building a docker image for loudgain? I was hoping to use it with my Synology NAS. Would appreciate your thoughts on this. Thanks

**Comment by joonas-fi** [comment]
For anybody looking for a Docker image, here's an interim solution for how you can build one yourself: https://github.com/Moonbase59/loudgain/pull/43#issuecomment-1094248851
